ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update   			\
      && apt-get -y install 		\
      python-catkin-tools 			\
      python-rosinstall-generator 	\
      ros-kinetic-rqt				\
      ros-kinetic-rqt-common-plugins

# ADD apt.conf /etc/apt/apt.conf
# ADD .gitconfig /root/.gitconfig
