# RUN apt-get -y update \
      # && apt-get -y install \
RUN apt-get -y install 			      \
      python-software-properties	\
      software-properties-common	\
      git							            \
      openssh-client				      \
      usbutils						        \
      wget 
  # \
  # && apt-get clean \
  # && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*